---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ray_ma.
--- DateTime: 2019/10/12 15:25
---
function max(num1, num2)
    if (num1 > num2) then
        result = num1
    else
        result = num2
    end
    return result
end
print(max(10, 6))
print(max(3, 7))
print(max(9, max(10, 2)))