---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ray_ma.
--- DateTime: 2019/10/12 15:22
---
for i = 10, 1, -1 do
    repeat
        if i == 5 then
            print("continue code here")
            break
        end
        print(i, "loop")

    until true
end